stages:
  - test
  - release

image: queeno/ubuntu-desktop

before_script:
  - apt-get update -y
  - apt-get install sudo -y
  - adduser --disabled-password --gecos '' docker
  - adduser docker sudo
  - echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers

test:
  script:
    - ./main.sh -s common -s dev -s desktop -s server -v
    
release:
  artifacts:
    paths:
      - main.sh
      - src
      - configsets
